# This is a basic workflow to help you get started with Actions

name: Build and deploy to AWS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Installs Pipfile Dependencies
      - name: Build
        run: |
          sudo pip install pipenv
          pipenv install --dev

      # Runs pytest
      - name: Test
        run: pipenv run python -m pytest ./src

      # Runs flake8
      - name: Linter
        run: pipenv run python -m flake8 ./src

      - name: Coverage check
        run: pipenv run python -m pytest ./src/tests/ --cov=. --cov-report=xml --cov-fail-under=95

      # TODO add pylint metric and coverage badge

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    defaults:
      run:
        working-directory: ./deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Package
      - name: Package lambda layer
        run: |
          cd ..
          sudo pip install pipenv
          pipenv install
          pipenv run pip freeze > requirements.txt
          mkdir python
          cd ./python/
          pip install -r ../requirements.txt -t ./
          cd ..
          zip -r python.zip python

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install CDK
        run: yarn

      - name: Test deployment
        run: yarn test

      - name: CDK Synth
        run: yarn cdk synth

      - name: CDK Diff
        run: yarn cdk diff

      - name: CDK Bootstrap
        run: yarn cdk bootstrap

      - name: Create artifact directory
        run: mkdir -p artifact

      - name: CDK Deploy
        run: yarn cdk deploy --outputs-file artifact/cdk-outputs.json --require-approval never

      - name: Upload cdk-outputs artifact
        uses: actions/upload-artifact@v2
        with:
          name: aws-artifacts
          path: deploy/artifact/cdk-outputs.json
          if-no-files-found: error
